Resources:
  ServerlessMSKSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: ServerlessVPC
    Properties:
      GroupDescription: Allow access to the public subnets
      VpcId: !Ref ServerlessVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          # should we allow ssh access?
      Tags:
        - Key: Name
          Value: ${self:service}-${self:provider.stage}-sg
