service: msk-kafka-${sls:stage}
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${sls:stage}
  region: ${env:AWS_REGION}

package:
  individually: true

custom:
  webpack:
    webpackConfig: webpack.config.cjs
    includeModules: true
    excludeFiles: ['./**/*.test.js']

resources:
  # we will add further resources here...
  - ${file('./resources/config/vpc.yml')}
