service: node-mongo-kafka-experiment
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${sls:stage}
  region: ${env:AWS_REGION}

package:
  individually: true

functions: ${file('./resources/lambda/functions.yml')}

custom:
  webpack:
    webpackConfig: webpack.config.cjs
    includeModules: true
    excludeFiles: ['./**/*.test.js']
resources:
  - ${file('./resources/config/vpc.yml')}
  - ${file('./resources/config/subnets.yml')}
  - ${file('./resources/config/igw.yml')}
  - ${file('./resources/config/route-private.yml')}
  - ${file('./resources/config/route-public.yml')}
  - ${file('./resources/config/security-groups.yml')}
  - ${file('./resources/apache-kafka/msk.yml')}
