Resources:
  ServerlessMSK:
    Type: AWS::MSK::Cluster
    Properties:
      ClusterName: ${self:service}-${self:provider.stage}-msk
      KafkaVersion: 2.6.2
      BrokerNodeGroupInfo:
        InstanceType: kafka.t3.small
        ClientSubnets:
          - !Ref ServerlessPrivateSubnet1
          - !Ref ServerlessPrivateSubnet2
          - !Ref ServerlessPrivateSubnet3
        SecurityGroups:
          - !Ref ServerlessMSKSecurityGroup
        StorageInfo:
          EbsStorageInfo:
            VolumeSize: 10
      NumberOfBrokerNodes: 3
      EncryptionInfo:
        EncryptionInTransit:
          ClientBroker: TLS
          InCluster: true
      OpenMonitoring:
        Prometheus:
          JmxExporter:
            EnabledInBroker: 'true'
          NodeExporter:
            EnabledInBroker: 'true'
      Tags:
        Key: Name
        Value: ${self:service}-${self:provider.stage}-msk
