name: Serverless Node Kafka CI Piepline
on: 
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i
      - name: Lint
        run: npm run lint:fix
      - name: Run test
        run: npm run test

      # - uses: artiomtr/jest-coverage-report-action@v2
      #   if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/staging'
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     threshold: 15
      #     package-manager: yarn
      #     test-script: yarn jest --silent --ci --coverage --testLocationInResults --json --outputFile="report.json"

      - name: Build
        run: npm run build
